### ISSUE TITLE
When two or more detail rows are open, errors occur by sorting table headers or clicking pagination buttons

### ISSUE THREAD

**Issue by sanderheilbron** [rafaelpimpa/buefy#423] opened 2017-11-19 00:05 UTC
Since Buefy version 0.6.1 issue #246 is back again.

**Buefy** version: 0.6.1
**Vuejs** version: 2.5.5
**OS/Browser**: MacOS 10.13.1 / Chrome 62

Although a detail-key is available, the following errors show up when opening the first detail row and sorting a column:
* [Vue warn]: It seems there are duplicate keys that is causing an update error. Make sure each v-for item has a unique key.
* [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'key' of undefined"
* TypeError: Cannot read property 'key' of undefined

A second issue that occurs is that rows disappear after sorting columns.

**Comment by rafaelpimpa** [comment] 2017-11-20 10:33
@wanxe can you take a look?

**Comment by wanxe** [comment] 2017-11-20 22:09
Of course @rafaelpimpa I think is fixed on  #426

**Closed** 2017-11-22 19:29 UTC

**Comment by wanxe** [comment] 2017-11-23 00:46
As you can see on the [video](https://mega.nz/#!UkoEEDSA!BdO7K9QBxXXI6E_XlCo-RH8ujsX4oTfWRZbIfSSeYoU) I can't reproduce the error, is possible to attach any fiddle? @sanderheilbron

**Comment by fdrews** [comment] 2018-01-01 18:42
Hello in my mind is not the correct solution to remove the :key from detail row. 

Possible solution is to add a pre or postfix to the keys. Here is the closed Vue issue [#7323](https://github.com/vuejs/vue/issues/7323) with the same explained problem.

Best regards Florian

**Comment by wanxe** [comment] 2018-01-01 19:19
Yes is a possible solution. Let me test it. Thanks sow much @fdrews :)

**Comment by fdrews** [comment] 2018-01-01 19:44
Your welcome and thank you for your great work. 

If you test it, you will get another errors for duplicate keys in the docs components.

**Comment by fdrews** [comment] 2018-01-02 20:31
Hello @wanxe i have detected the other duplicate key errors. The ApiView in docs/components have also a duplicate key. The duplicate key is responsible for all docs errors where the apiview have a title attribute in seperates components api folder.

Regards flo

**Comment by wanxe** [comment] 2018-01-02 22:13
Can you provide any link? I think is the new Vue version. Is more sensible with the component :keys. 
But you can do a PR if you feel confident 😄

**Comment by fdrews** [comment] 2018-01-02 22:29
If I understand correctly, there was no error message in an earlier version (< 2.5.10). But the error already existed. :D

**Comment by wanxe** [comment] 2018-01-02 23:56
@fdrews I test some components and didn't saw any warning about that. Anyway I've added again the :key prop of the detailed row with an prefix and works fine.
Now need wait to the owners to merge my changes or not. Meanwhile, can you provide the exact links/components that fails?

Or better, clone the dev repo and run `npm run dev`, navigate to the component and tell me. I would be very grateful, since I can't reproduce the errors.

**Comment by fdrews** [comment] 2018-01-03 11:05
hey @wanxe i try my best to explain where you can find the other warnings. 

The warning is thrown by `/docs/components/ApiView.vue`.

So if you would reproduce the warnings you have to start the dev environment, browse on the site to documentation and navigate to ui components an select for example "Table".

So you will get this warnings:
`[Vue warn]: Duplicate keys detected: 'Table'. This may cause an update error.`
`[Vue warn]: Duplicate keys detected: 'Column'. This may cause an update error.`

**Comment by wanxe** [comment] 2018-01-03 22:14
I don't know man, but don't see any warning 😿
